name: Build Test

on: push

jobs:
  build-mbedtls:
    name: CMake Project Example (MbedTLS)
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/checkout@v3
        with:
          repository: Mbed-TLS/mbedtls
          ref: v2.28.1
          path: mbedtls

      - name: Prepare Sysroot
        id: pi-sysroot
        uses: mariotaku/raspbian-sysroot-action@main

      - name: Install Build Tools
        shell: bash
        # apt-get update was implicitly called, so we don't have to call it here
        run: sudo apt-get -y -qq install crossbuild-essential-armhf cmake

      - name: Build Project
        working-directory: mbedtls
        run: |
          cmake -E make_directory build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=${{steps.pi-sysroot.outputs.cmake-toolchain}}
          cmake --build .

  build-opus:
    name: CMake Project Example (Autoconf)
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/checkout@v3
        with:
          repository: xiph/opus
          ref: v1.3.1
          path: opus

      - name: Prepare Sysroot
        id: pi-sysroot
        uses: mariotaku/raspbian-sysroot-action@main

      - name: Install Build Tools
        shell: bash
        # apt-get update was implicitly called, so we don't have to call it here
        run: sudo apt-get -y -qq install crossbuild-essential-armhf

      - name: Build Project
        working-directory: opus
        env:
          CC: arm-linux-gnueabihf-gcc
          CXX: arm-linux-gnueabihf-g++
          LD: arm-linux-gnueabihf-ld
        run: |
          source ${{steps.pi-sysroot.outputs.shell-envsetup}}
          ./autogen.sh
          ./configure --host=arm-linux-gnueabihf
          make
